// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0jmQw5gKoztNtWjlFMqSMacXxNwRoy9c',
    appId: '1:68241899379:web:56c8b5977862c102c78f06',
    messagingSenderId: '68241899379',
    projectId: 'muklog',
    authDomain: 'muklog.firebaseapp.com',
    storageBucket: 'muklog.firebasestorage.app',
    measurementId: 'G-VQ4CT931VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT6XMgOLvu_P8R8zFfjgUGS26XSqknSsw',
    appId: '1:68241899379:android:e1ed788e8fb10354c78f06',
    messagingSenderId: '68241899379',
    projectId: 'muklog',
    storageBucket: 'muklog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZERRw7oeAxXsiKR_ARRzja9u4KaRoUpY',
    appId: '1:68241899379:ios:1bffeb63fc89e4a5c78f06',
    messagingSenderId: '68241899379',
    projectId: 'muklog',
    storageBucket: 'muklog.firebasestorage.app',
    iosBundleId: 'com.jylee.muklog',
  );
}
